name: Count Lines of Code

on: [push, pull_request]

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count lines of code
        uses: toomm/cloc-action@v1
